name: multimodal-access-vaw
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - pandas
  - httpx
  - numpy
  - scipy
  - shapely
  - pyproj
  - fiona
  - rasterio
  - networkx
  - osmnx
  - pyogrio
  - jupyterlab
  - matplotlib
  - seaborn
  - pyyaml
  - pytest
  - ruff
  - pip
